"""
PDF report generation.

Clinicians want a document they can attach to a record, not a browser tab.
Renders the prediction, Grad-CAM++ overlay, measurements and disclaimer.
"""

from __future__ import annotations

import base64
import io
import json
from datetime import UTC, datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

DISCLAIMER = (
    "This report was generated by an automated clinical decision-support tool. "
    "It is <b>not</b> a certified medical device and does not constitute a diagnosis. "
    "All findings must be reviewed and confirmed by a qualified healthcare professional "
    "before any clinical decision is made."
)

_ACCENT = colors.HexColor("#1f4e79")
_MUTED = colors.HexColor("#5a6472")


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("Title", parent=base["Title"], fontSize=20, textColor=_ACCENT, spaceAfter=2),
        "subtitle": ParagraphStyle("Subtitle", parent=base["Normal"], fontSize=9, textColor=_MUTED, spaceAfter=12),
        "h2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=12, textColor=_ACCENT, spaceBefore=12, spaceAfter=6),
        "body": ParagraphStyle("Body", parent=base["Normal"], fontSize=9.5, leading=13),
        "small": ParagraphStyle("Small", parent=base["Normal"], fontSize=7.5, textColor=_MUTED, leading=10),
    }


def _table(rows: list[list[str]], col_widths: list[float]) -> Table:
    table = Table(rows, colWidths=col_widths, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef3f8")),
        ("TEXTCOLOR", (0, 0), (-1, 0), _ACCENT),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c8d2dd")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return table


def _image_from_base64(b64: str, width: float, height: float) -> Image | None:
    if not b64:
        return None
    try:
        return Image(io.BytesIO(base64.b64decode(b64)), width=width, height=height)
    except Exception:
        return None


def _fmt_dt(value: datetime | None) -> str:
    if value is None:
        return "—"
    return value.strftime("%Y-%m-%d %H:%M UTC")


def build_study_report(study, build: dict, timeline: list | None = None) -> bytes:
    """
    Render a Study ORM row into a PDF.

    timeline, when supplied, adds a prior-scan comparison page.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
        title=f"BrainScan AI Report {study.id}",
    )
    st = _styles()
    flow: list = []

    flow.append(Paragraph("BrainScan AI — MRI Analysis Report", st["title"]))
    flow.append(Paragraph(
        f"Report ID {study.id} &nbsp;|&nbsp; Generated {_fmt_dt(datetime.now(UTC))}",
        st["subtitle"],
    ))

    flow.append(Paragraph("Study Details", st["h2"]))
    flow.append(_table([
        ["Field", "Value"],
        ["Patient ID", study.patient_id or "Not supplied"],
        ["Source file", study.filename or "—"],
        ["Analysed at", _fmt_dt(study.created_at)],
        ["Image SHA-256", (study.image_sha256 or "")[:32] + "…"],
        ["MRI sequence", study.sequence_type or "Not detected"],
        ["Image quality", f"{study.quality_score:.0f} / 100" if study.quality_score is not None else "—"],
    ], [45 * mm, 125 * mm]))

    flow.append(Paragraph("AI Findings", st["h2"]))
    probabilities = {}
    if study.probabilities:
        try:
            probabilities = json.loads(study.probabilities)
        except (ValueError, TypeError):
            probabilities = {}

    findings = [
        ["Field", "Value"],
        ["Predicted class", study.predicted_class],
        ["Confidence", f"{study.confidence * 100:.1f}%"],
        ["Uncertainty (MC Dropout)", f"{study.uncertainty * 100:.1f}%" if study.uncertainty is not None else "—"],
        ["WHO grade estimate", study.who_grade or "—"],
        ["Flagged for review", "YES" if study.flagged_for_review else "No"],
    ]
    if study.is_ood:
        findings.append(["Distribution check", "OUT OF DISTRIBUTION — result unreliable"])
    flow.append(_table(findings, [45 * mm, 125 * mm]))

    if probabilities:
        flow.append(Spacer(1, 6))
        rows = [["Class", "Probability"]]
        rows += [[name, f"{float(value):.1f}%" if float(value) > 1 else f"{float(value) * 100:.1f}%"]
                 for name, value in probabilities.items()]
        flow.append(_table(rows, [45 * mm, 125 * mm]))

    if study.tumor_volume_mm3 is not None:
        flow.append(Paragraph("Volumetry", st["h2"]))
        flow.append(_table([
            ["Measurement", "Value"],
            ["Tumor volume", f"{study.tumor_volume_mm3:.1f} mm3 ({study.tumor_volume_mm3 / 1000:.2f} cm3)"],
            ["Tumor area", f"{study.tumor_area_px:.0f} px" if study.tumor_area_px is not None else "—"],
        ], [45 * mm, 125 * mm]))

    overlay = _image_from_base64(study.gradcam_overlay or "", width=80 * mm, height=80 * mm)
    if overlay is not None:
        flow.append(Paragraph("Explainability — Grad-CAM++", st["h2"]))
        flow.append(overlay)
        flow.append(Spacer(1, 4))
        flow.append(Paragraph(
            "Warmer regions contributed most to the prediction. This highlights model "
            "attention and is not a validated tumor boundary.", st["small"],
        ))

    if study.feedback is not None:
        flow.append(Paragraph("Radiologist Review", st["h2"]))
        flow.append(_table([
            ["Field", "Value"],
            ["Reviewer", study.feedback.reviewer or "—"],
            ["Confirmed class", study.feedback.corrected_class],
            ["Agrees with AI", "Yes" if study.feedback.agrees_with_ai else "No"],
            ["Notes", study.feedback.notes or "—"],
        ], [45 * mm, 125 * mm]))

    if timeline and len(timeline) > 1:
        flow.append(PageBreak())
        flow.append(Paragraph("Longitudinal Comparison", st["h2"]))
        rows = [["Date", "Class", "Confidence", "Volume (cm3)"]]
        for scan in timeline:
            rows.append([
                _fmt_dt(scan.created_at),
                scan.predicted_class,
                f"{scan.confidence * 100:.1f}%",
                f"{scan.tumor_volume_mm3 / 1000:.2f}" if scan.tumor_volume_mm3 else "—",
            ])
        flow.append(_table(rows, [45 * mm, 40 * mm, 35 * mm, 40 * mm]))

    flow.append(Spacer(1, 14))
    flow.append(Paragraph("Disclaimer", st["h2"]))
    flow.append(Paragraph(DISCLAIMER, st["small"]))
    flow.append(Spacer(1, 6))
    flow.append(Paragraph(
        f"Model {build.get('model_version')} &nbsp;|&nbsp; API {build.get('api_version')} "
        f"&nbsp;|&nbsp; build {build.get('git_sha')}",
        st["small"],
    ))

    doc.build(flow)
    return buffer.getvalue()
